name: tic_tac_toe
version: 0.0.2
description: An Angular 2 and Polymer Dart application -- Tic-Tac-Toe! Two-player only.

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  analyzer: 0.27.2
  angular2: ^2.0.0-beta.17
  browser: ^0.10.0
  polymer: ^1.0.0-rc.17
  polymer_elements: ^1.0.0-rc.8
  web_components: ^0.12.0
  logging: any
  intl: any

transformers:
- polymer:
    entry_points: web/index.html
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
